### ISSUE TITLE
Security listing displays incorrect FileVault status for Big Sur clients

### ISSUE THREAD

**Issue by MichalMMac** [munkireport/security#17]
Security Report listing displays incorrect `Encryption Status: Unencrypted` label for Big Sur clients with Filevault 2 enabled.

Storage section (`diskreport` table) has correct information about the state of encryption for each APFS volume:

- `/` - Not Encrypted
- `/System/Volumes/Data` - **Encrypted**
- `/System/Volumes/Preboot` - Not Encrypted
- `/System/Volumes/VM` - Not Encrypted
- `/System/Volumes/Update` - Not Encrypted

Filevault secion (`filevault_statue` table) also have correct information about state of the FIlevault 2: `FileVault Status: ON` and `FileVault Enabled Users: xyz`.

I think security listing view is probably getting the `Encryption Status: Unencrypted` from information about the `/` root volume which is not encrypted since 11.0 Big Sur.

**Comment by tuxudo** [comment]
This should be resolved in pull request #24
