### ISSUE TITLE
Returns incorrect data

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/security#7]
I have ARD and SSH set to allow specific users - but MR shows All users permitted https://macadmins.slack.com/archives/C066NK3K5/p1553196335777000

**Comment by rickheil** [comment]
From slack - access is granted to specific users via system prefs -> remote login. @ofirgalcon what OS is this happening on, multiple?

**Comment by ofirgalcon** [comment]
10.14.3

Ofir on iPhone

**Comment by tuxudo** [comment]
Is this still an issue?
