### ISSUE TITLE
Error with groups where there is a blank

### ISSUE THREAD

**Issue by micneu72** [munkireport/security#9]
macOS 10.14.4
munkireport 4.0.2
macOS is AD Member

Error:
Munkireport: Running security.py
    Munkireport: security.py Error: There was an unknown error.
Traceback (most recent call last):
  File "/usr/local/munki/preflight.d/security.py", line 411, in <module>
    main()
  File "/usr/local/munki/preflight.d/security.py", line 398, in main
    result.update({'ssh_groups': ssh_group_access_check()})
  File "/usr/local/munki/preflight.d/security.py", line 134, in ssh_group_access_check
    group_list.append(grp.getgrgid(group_id_out.split()[1]).gr_name)
IndexError: list index out of range
WARNING: Munkireport: security.py return code: 1
    Munkireport: Running softwareupdate.sh

**Comment by poundbangbash** [comment]
This should be addressed in commit https://github.com/munkireport/security/commit/1e156eb620d17fc8194c5252116587c160e4527a

Update the security module to the latest code, update the client and let us know if the issue is resolved.
